### ISSUE TITLE
Microarrays data, often above 100%

### ISSUE THREAD

**Issue by zingobele** [giannimonaco/ABIS#15]
Dear Gianni, 

Thank you for the wonderful work, very useful for present and future immunological research. 
I am running ABIS on R, I use PBMCs microarray data. Unfortunately, I obtain most often than not, cumulative abundance higher than 100 (range 88- 151). I have read how to deal with negative values, but I am wondering if those results could be trusted and how to deal with this. I could scale all the samples to 100 (but I guess I will lose some information) or just compare the relative abundances for each cell tipe. Any suggestion?

Thanks in advance, 

Edoardo

**Comment by giannimonaco** [comment]
Dear Edoardo,

Thank you for the appreciation!
I guess that if you want to compare different samples, it might be better not to scale the values. If you scale the values, you assume there is no unknown content and the spread is only due to technical variability.
One thing you could do is to scale all the value so that the one with higher cumulative abundance is 100. This could help with the visualization.

I hope this helps.
Best wishes,
Gianni

**Comment by zingobele** [comment]
Thank you!
